services:
  - type: web
    name: planarity-testing-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api.app:app"
    port: 10000
    plan: free